---
- name: Ensure RKE2 config directory exists
  ansible.builtin.file:
    path: "/etc/rancher/rke2"
    state: directory
    mode: '0755'
    owner: root
    group: root
  become: true

- name: Download RKE2 agent installation script
  ansible.builtin.get_url:
    url: https://get.rke2.io
    dest: /tmp/rke2-install.sh
    mode: '0700'
  become: true

