---
- name: Ensure RKE2 config directory exists
  ansible.builtin.file:
    path: "/etc/rancher/rke2"
    state: directory
    mode: '0755'
    owner: root
    group: root
  become: true

- name: Download RKE2 agent installation script
  ansible.builtin.get_url:
    url: https://get.rke2.io
    dest: /tmp/rke2-install.sh
    mode: '0700'
  become: true

- name: Install RKE2 agent
  ansible.builtin.command: INSTALL_RKE2_TYPE=agent /tmp/rke2-install.sh
  args:
    creates: /usr/local/bin/rke2
  become: true

- name: Fetch rke2_token from first server node
  ansible.builtin.set_fact:
    rke2_token: "{{ hostvars[groups['server_nodes'][0]]['rke2_token'] }}"

- name: Debug - Display rke2_token in add-agent role
  ansible.builtin.debug:
    var: rke2_token
    verbosity: 2

- name: Set decoded token fact
  ansible.builtin.set_fact:
    decoded_rke2_token: "{{ rke2_token }}"

- name: Deploy RKE2 Agent Configuration
  ansible.builtin.template:
    src: templates/rke2-agent-config.j2
    dest: /etc/rancher/rke2/config.yaml
    owner: root
    group: root
    mode: '0644'
    force: "{{ overwrite_agent_config | default(false) }}"
  become: true
  when: rke2_token is defined
  
- name: Debug - Display rke2_token in add-agent role
  ansible.builtin.debug:
    var: rke2_token
    verbosity: 2

- name: Create RKE2 agent service file
  ansible.builtin.template:
    src: templates/rke2-agent.service.j2
    dest: /etc/systemd/system/rke2-agent.service
    owner: root
    group: root
    mode: '0644'
    force: "{{ overwrite_agent_config | default(false) }}"
  become: true

- name: Ensure RKE2 agents are enabled and running
  ansible.builtin.systemd:
    name: rke2-agent
    state: started
    enabled: true
    daemon_reload: yes
  become: true

- name: Restart rke2-agent service
  ansible.builtin.systemd:
    name: rke2-agent
    state: restarted
  become: true
