---
- name: Gather disk information
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Get list of all block devices with filesystem info
      command: lsblk -nfo NAME,SIZE,TYPE,FSTYPE,MOUNTPOINT
      register: block_devices
      changed_when: false

    - name: Get root filesystem device
      command: findmnt -no SOURCE /
      register: root_fs
      changed_when: false

    - name: Get LVM information
      command: pvs --noheadings -o pv_name,vg_name
      register: lvm_info
      changed_when: false

    - name: Parse and display disk information
      ansible.builtin.set_fact:
        disk_info: "{{ disk_info | default([]) + [{'name': item.split()[0], 'size': item.split()[1], 'type': item.split()[2], 'fstype': item.split()[3] if item.split() | length > 3 else 'N/A', 'mountpoint': item.split()[4] if item.split() | length > 4 else 'N/A'}] }}"
      loop: "{{ block_devices.stdout_lines }}"

    - name: Display disk information
      ansible.builtin.debug:
        msg: 
          - "Device: {{ item.name }}"
          - "Size: {{ item.size }}"
          - "Type: {{ item.type }}"
          - "Filesystem: {{ item.fstype }}"
          - "Mountpoint: {{ item.mountpoint }}"
          - "OS Device: {{ 'Yes' if item.name in root_fs.stdout else 'No' }}"
          - "LVM: {{ 'Yes' if item.name in lvm_info.stdout else 'No' }}"
      loop: "{{ disk_info }}"

    - name: Summary
      ansible.builtin.debug:
        msg:
          - "Total devices: {{ disk_info | length }}"
          - "OS Device: {{ root_fs.stdout }}"
          - "Devices used in LVM: {{ lvm_info.stdout_lines | map('regex_replace', '^\\s*(.*)\\s+.*$', '\\1') | list | join(', ') }}"
