---
- name: Gather disk information and save to file
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    remote_output_file: "/tmp/disk_info_{{ inventory_hostname }}.json"
    local_output_dir: "./disk_info_output"

  tasks:
    - name: Get list of all block devices with filesystem info
      command: lsblk -nfo NAME,SIZE,TYPE,FSTYPE,MOUNTPOINT
      register: block_devices
      changed_when: false

    - name: Get root filesystem device
      command: findmnt -no SOURCE /
      register: root_fs
      changed_when: false

    - name: Get LVM information
      command: pvs --noheadings -o pv_name,vg_name
      register: lvm_info
      changed_when: false

    - name: Parse disk information
      set_fact:
        disk_info: "{{ disk_info | default([]) + [{'name': item.split()[0], 'size': item.split()[1], 'type': item.split()[2], 'fstype': item.split()[3] if item.split() | length > 3 else 'N/A', 'mountpoint': item.split()[4] if item.split() | length > 4 else 'N/A'}] }}"
      loop: "{{ block_devices.stdout_lines }}"

    - name: Prepare disk information for output
      set_fact:
        output_info:
          hostname: "{{ inventory_hostname }}"
          total_devices: "{{ disk_info | length }}"
          os_device: "{{ root_fs.stdout }}"
          lvm_devices: "{{ lvm_info.stdout_lines | map('regex_replace', '^\\s*(.*)\\s+.*$', '\\1') | list }}"
          devices: "{{ disk_info | map(attribute='name') | list }}"
          disk_details: "{{ disk_info }}"

    - name: Write disk information to file on remote host
      copy:
        content: "{{ output_info | to_nice_json }}"
        dest: "{{ remote_output_file }}"

    - name: Ensure local output directory exists
      file:
        path: "{{ local_output_dir }}"
        state: directory
      delegate_to: localhost
      become: no

    - name: Fetch disk information file from remote host
      fetch:
        src: "{{ remote_output_file }}"
        dest: "{{ local_output_dir }}/{{ inventory_hostname }}_disk_info.json"
        flat: yes
      become: no

    - name: Remove temporary file from remote host
      file:
        path: "{{ remote_output_file }}"
        state: absent

- name: Collect all disk information files
  hosts: localhost
  gather_facts: no
  
  vars:
    collected_file: "disk_info_all_hosts.json"
    local_output_dir: "./disk_info_output"

  tasks:
    - name: Find all disk info files
      find:
        paths: "{{ local_output_dir }}"
        patterns: "*_disk_info.json"
      register: found_files

    - name: Read disk info files
      slurp:
        src: "{{ item.path }}"
      register: file_contents
      loop: "{{ found_files.files }}"

    - name: Combine all disk info
      set_fact:
        all_disk_info: "{{ all_disk_info | default([]) + [item.content | b64decode | from_json] }}"
      loop: "{{ file_contents.results }}"

    - name: Write combined disk information to file
      copy:
        content: "{{ all_disk_info | to_nice_json }}"
        dest: "{{ local_output_dir }}/{{ collected_file }}"

    - name: Notify about combined file creation
      debug:
        msg: "Combined disk information for all hosts has been saved to {{ local_output_dir }}/{{ collected_file }}"
