---
- name: Collect all disk information files
  hosts: localhost
  connection: local
  gather_facts: no
  
  vars:
    collected_file: "disk_info_all_hosts.json"
    local_output_dir: "./disk_info_output"

  tasks:
    - name: Ensure local output directory exists
      file:
        path: "{{ local_output_dir }}"
        state: directory

    - name: Find all disk info files
      find:
        paths: "{{ local_output_dir }}"
        patterns: "*_disk_info.json"
      register: found_files

    - name: Read disk info files
      slurp:
        src: "{{ item.path }}"
      register: file_contents
      loop: "{{ found_files.files }}"

    - name: Combine all disk info
      set_fact:
        all_disk_info: "{{ all_disk_info | default([]) + [item.content | b64decode | from_json] }}"
      loop: "{{ file_contents.results }}"

    - name: Write combined disk information to file
      copy:
        content: "{{ all_disk_info | to_nice_json }}"
        dest: "{{ local_output_dir }}/{{ collected_file }}"

    - name: Notify about combined file creation
      debug:
        msg: "Combined disk information for all hosts has been saved to {{ local_output_dir }}/{{ collected_file }}"